/*
Shows total spend per customer.
Used to identify high-value customers.
*/
SELECT
	CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
	ROUND(SUM(OI.QUANTITY * P.PRICE), 2) AS TOTAL_SPEND
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
	JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
	JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	C.CUSTOMER_ID,
	CUSTOMER_NAME
ORDER BY
	TOTAL_SPEND DESC
